services:
  dashboard:
    image: dashboard
    env_file:
      - .env
    ports:
      - 8050:8050
    volumes:
      - ./:/fall25-uva-ds6600-climatefuture-jf
    networks:
      - dbnetwork

  postgres:
    image: postgres:17.6

    env_file:
    - .env
  
    ports:
    - 5432:5432

    volumes:
    - postgresdata:/var/lib/postgresql/data
  
    networks:
    - dbnetwork

  mysql:
    image: mysql

    env_file:
    - .env

    ports:
    - 3306:3306

    volumes:
    - mysqldata:/var/lib/mysql

    networks:
    - dbnetwork

volumes:
  postgresdata:
  mysqldata:

networks:
  dbnetwork: