services:
  climatefuture:
    image: futurehomedocker
    env_file:
      - .env
    ports:
      - 8888:8888
    volumes:
      - ./:/fall25-uva-ds6600-climatefuture-jf
    networks:
      - dbnetwork

  postgres:
    image: postgres:17.6

    env_file:
    - .env
  
    ports:
    - 5432:5432

    volumes:
    - postgresdata:/var/lib/postgresql/data
  
    networks:
    - dbnetwork

  mysql:
    image: futurehomesql

    #Questions 1: What environmental variables are required by this image?
    env_file:
    - .env

    #Question 2: Does the software have a port (inside the container) it runs on by default?
    ports:
    - 3306:3306

    #Question 3: What folder inside the container stores the data you need to save?
    volumes:
    - mysqldata:/var/lib/mysql

    networks:
    - dbnetwork

volumes:
  postgresdata:

networks:
  dbnetwork: