services:
  climatefuture:
    image: futurehomedocker
    env_file:
      - .env
    ports:
      - 8888:8888
    volumes:
      - ./:/fall25-uva-ds6600-climatefuture-jf
    networks:
      - dbnetwork

  postgres:
    image: postgres:17.6

    env_file:
    - .env
  
    ports:
    - 5432:5432

    volumes:
    - postgresdata:/var/lib/postgresql/data
  
    networks:
    - dbnetwork

volumes:
  postgresdata:

networks:
  dbnetwork: